# Generated by Django 5.1.1 on 2024-09-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVehiculos', '0002_alter_vehiculo_matricula_alter_vehiculo_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='matricula',
            field=models.CharField(max_length=15),
        ),
    ]
