# Generated by Django 5.1.1 on 2024-09-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVehiculos', '0003_alter_propietario_email_alter_vehiculo_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha_hora_entrada',
            field=models.DateTimeField(),
        ),
    ]
